apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-deployment
  labels:
    app: expense-tracker
spec:
  replicas: 2   # run 2 pods for redundancy
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: shorya604/expense-tracker:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
