apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  selector:
    app: expense-tracker
  ports:
    - protocol: TCP
      port: 80        # external port
      targetPort: 3000 # container port
  type: NodePort      # use LoadBalancer in cloud (EKS/GKE/AKS)
